name: Manually triggered release
on: workflow_dispatch

jobs:
  build:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
      - run: sudo apt-get update -y && sudo apt-get install -y libguestfs-tools
      - name: Build the archive
        run: ./build
      - uses: actions/upload-artifact@v2
        with:
          name: Alma-8.zip
          path: ./dist/Alma-8.zip
